version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile  # O caminho para o Dockerfile dentro da pasta docker
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Ducilio199@
      - MYSQL_DATABASE=vitrin_events
